backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: public/assets
public_folder: /assets
collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "_posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Excerpt", name: "excerpt", widget: "string" }
      - { label: "Cover Image", name: "coverImage", widget: "image" }
      - { label: "Date", name: "date", widget: "datetime", default: "{{now}}" }
      - label: "Author"
        name: "author"
        widget: "object"
        fields:
          - { label: "Name", name: "name", widget: "string" }
          - { label: "Picture", name: "picture", widget: "image" }
      - label: "OG Image"
        name: "ogImage"
        widget: "object"
        fields:
          - { label: "URL", name: "url", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
